version: '2.3'
services:
    shell:
        build: .
        volumes:
            - $PWD:/root/workspace
        working_dir: /root/workspace
        ipc: host
        environment:
            - TZ=Asia/Tokyo
        entrypoint: bash
    python:
        build: .
        volumes:
            - $PWD:/root/workspace
        working_dir: /root/workspace
        ipc: host
        environment:
            - TZ=Asia/Tokyo
        entrypoint: python
    jn:
        build: .
        volumes:
            - $PWD:/root/workspace
        working_dir: /root/workspace/notebooks
        ipc: host
        environment:
            - TZ=Asia/Tokyo
        ports:
            - 8888:8888
        command: jupyter notebook --port 8888 --ip=0.0.0.0 --allow-root
